#!/bin/bash

export PULP_SERVER=http://192.168.121.174:8080
export PULP_API=/pulp/api/v3

http POST ${PULP_SERVER}${PULP_API}/repositories/ name=foo

http POST ${PULP_SERVER}${PULP_API}/remotes/file/ name='bar' url='https://repos.fedorapeople.org/pulp/pulp/demo_repos/test_file_repo/PULP_MANIFEST'

http POST ${PULP_SERVER}${PULP_API}/remotes/file/1/sync/ repository=${PULP_API}/repositories/1/ mirror=True

http GET ${PULP_SERVER}${PULP_API}/remotes/file/1/versions/1/

http --form POST ${PULP_SERVER}${PULP_API}/artifacts/ file@./foo.tar.gz

http POST ${PULP_SERVER}${PULP_API}/content/file/files/ relative_path=foo.tar.gz artifact="/pulp/api/v3/artifacts/1/"

export CONTENT_HREF=$(http ${PULP_SERVER}${PULP_API}/content/file/files/ | jq -r '.results[] | select(.relative_path == "foo.tar.gz") | ._href')

http POST ${PULP_SERVER}${PULP_API}/repositories/1/versions/ add_content_units:="[\"$CONTENT_HREF\"]"

http POST ${PULP_SERVER}${PULP_API}/publishers/file/ name=bar
export PUBLISHER_HREF=$(http ${PULP_SERVER}${PULP_API}/publishers/file/ | jq -r '.results[] | select(.name == "bar") | ._href')

http POST ${PULP_SERVER}''$PUBLISHER_HREF'publish/' repository=${REPO_HREF}

export PUBLICATION_HREF=$(http ${PULP_SERVER}${PULP_API}/publications/ | jq -r --arg PUBLISHER_HREF "$PUBLISHER_HREF" '.results[] | select(.publisher==$PUBLISHER_HREF) | ._href')

http POST ${PULP_SERVER}${PULP_API}/distributions/ name='baz' base_path='foo' publication=$PUBLICATION_HREF
