#!/bin/bash

export PULP_SERVER=http://pulp-http-pulp.192.168.42.15.nip.io

http POST http://pulp-http-pulp.192.168.42.15.nip.io/pulp/api/v3/repositories/ name=foo
export REPO_HREF=$(http http://pulp-http-pulp.192.168.42.15.nip.io/pulp/api/v3/repositories/ | jq -r '.results[] | select(.name == "foo") | ._href')

http POST http://pulp-http-pulp.192.168.42.15.nip.io/pulp/api/v3/remotes/file/ name='bar' url='https://repos.fedorapeople.org/pulp/pulp/demo_repos/test_file_repo/PULP_MANIFEST'
export REMOTE_HREF=$(http http://pulp-http-pulp.192.168.42.15.nip.io/pulp/api/v3/remotes/file/ | jq -r '.results[] | select(.name == "bar") | ._href')

http POST $PULP_SERVER''$REMOTE_HREF'sync/' repository=$REPO_HREF mirror=True

http GET $PULP_SERVER''$REPO_HREF'versions/1/'

http --form POST http://pulp-http-pulp.192.168.42.15.nip.io/pulp/api/v3/artifacts/ file@./foo.tar.gz

http POST http://pulp-http-pulp.192.168.42.15.nip.io/pulp/api/v3/content/file/files/ relative_path=foo.tar.gz artifact="/pulp/api/v3/artifacts/1/"

export CONTENT_HREF=$(http http://pulp-http-pulp.192.168.42.15.nip.io/pulp/api/v3/content/file/files/ | jq -r '.results[] | select(.relative_path == "foo.tar.gz") | ._href')

http POST $PULP_SERVER''$REPO_HREF'versions/' add_content_units:="[\"$CONTENT_HREF\"]"

http POST http://pulp-http-pulp.192.168.42.15.nip.io/pulp/api/v3/publishers/file/ name=bar
export PUBLISHER_HREF=$(http http://pulp-http-pulp.192.168.42.15.nip.io/pulp/api/v3/publishers/file/ | jq -r '.results[] | select(.name == "bar") | ._href')

http POST $PULP_SERVER''$PUBLISHER_HREF'publish/' repository=$REPO_HREF

export PUBLICATION_HREF=$(http http://pulp-http-pulp.192.168.42.15.nip.io/pulp/api/v3/publications/ | jq -r --arg PUBLISHER_HREF "$PUBLISHER_HREF" '.results[] | select(.publisher==$PUBLISHER_HREF) | ._href')

http POST http://pulp-http-pulp.192.168.42.15.nip.io/pulp/api/v3/distributions/ name='baz' base_path='foo' publication=$PUBLICATION_HREF
