---
- hosts: localhost
  gather_facts: no
  vars:
    minishift: true
    cluster_up: false
    project_name: pulp
    deployment_state: present
    version: latest
  pre_tasks:
    - shell: minishift ip
      register: minishift_ip
      when: minishift

    - set_fact:
        application_hostname: "pulp.{{ minishift_ip.stdout }}.nip.io"
      when: minishift

    - name: 'Login as system:admin'
      command: oc login -u system:admin

    - name: Add anyuid scc to anyuid service account
      command: oc adm policy add-scc-to-user anyuid system:serviceaccount:{{ project_name }}:{{project_name }}-anyuid
      when: minishift or cluster_up

    - name: 'Login as system:admin'
      command: oc login -u developer -p a

    - name: project pulp (workaround for https://github.com/ansible/ansible/issues/42116)
      shell: "oc new-project '{{ project_name }}' --description=\"{{ project_name }} Stack\" --display-name=\"{{ project_name }}\" || oc get project '{{ project_name }}'"
      when: minishift == true

    - name: 'service account'
      k8s:
        state: "{{ deployment_state }}"
        definition: "{{ lookup('template', 'pulp-operator/deploy/pulp-operator.serviceaccount.yaml') | from_yaml }}"

- import_playbook: pulp-operator/playbook.yaml
  vars:
    version: latest
