#!/bin/bash

/usr/bin/wait_on_postgres.py

scl enable rh-python36 "pulp-manager migrate --noinput auth"
scl enable rh-python36 "pulp-manager migrate --noinput"
scl enable rh-python36 "pulp-manager reset-admin-password --password admin"

scl enable rh-python36 "pulp-manager migrate --noinput pulp_file"

scl enable rh-python36 "pulp-manager migrate --noinput pulp_ansible"

exec "$@"
