#!/bin/bash

pushd pulp-operator

oc login -u developer -p a
docker login -u developer -p $(oc whoami -t) `minishift openshift registry`
docker build -t `minishift openshift registry`/pulp/pulp-operator:latest .
docker push `minishift openshift registry`/pulp/pulp-operator:latest

popd

oc create -f pulp-operator/deploy/operator.yaml || true
oc set image deployment/pulp-operator pulp-operator=`minishift openshift registry`/pulp/pulp-operator:latest

pod=$(oc get pods | grep pulp-operator | grep -v Terminating | awk '{print $1;}')
echo $pod
oc delete pods $pod || true

sleep 8

pod=$(oc get pods | grep pulp-operator | grep -v Terminating | awk '{print $1;}')
echo $pod

oc logs $pod --follow
